// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: blog-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogService_NewBlogPost_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	HeadlineText string   `protobuf:"bytes,2,opt,name=headline_text,json=headlineText,proto3" json:"headline_text,omitempty"`
	SummaryText  string   `protobuf:"bytes,3,opt,name=summary_text,json=summaryText,proto3" json:"summary_text,omitempty"`
	Tags         []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Images       []string `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Attachments  []string `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Refs         []string `protobuf:"bytes,7,rep,name=refs,proto3" json:"refs,omitempty"`
	Content      string   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BlogService_NewBlogPost_Params) Reset() {
	*x = BlogService_NewBlogPost_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_NewBlogPost_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_NewBlogPost_Params) ProtoMessage() {}

func (x *BlogService_NewBlogPost_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_NewBlogPost_Params.ProtoReflect.Descriptor instead.
func (*BlogService_NewBlogPost_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{0}
}

func (x *BlogService_NewBlogPost_Params) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BlogService_NewBlogPost_Params) GetHeadlineText() string {
	if x != nil {
		return x.HeadlineText
	}
	return ""
}

func (x *BlogService_NewBlogPost_Params) GetSummaryText() string {
	if x != nil {
		return x.SummaryText
	}
	return ""
}

func (x *BlogService_NewBlogPost_Params) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BlogService_NewBlogPost_Params) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BlogService_NewBlogPost_Params) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *BlogService_NewBlogPost_Params) GetRefs() []string {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *BlogService_NewBlogPost_Params) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BlogService_SaveBlogPost_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (x *BlogService_SaveBlogPost_Params) Reset() {
	*x = BlogService_SaveBlogPost_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_SaveBlogPost_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_SaveBlogPost_Params) ProtoMessage() {}

func (x *BlogService_SaveBlogPost_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_SaveBlogPost_Params.ProtoReflect.Descriptor instead.
func (*BlogService_SaveBlogPost_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlogService_SaveBlogPost_Params) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type BlogService_SaveBlogPost_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_SaveBlogPost_Response) Reset() {
	*x = BlogService_SaveBlogPost_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_SaveBlogPost_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_SaveBlogPost_Response) ProtoMessage() {}

func (x *BlogService_SaveBlogPost_Response) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_SaveBlogPost_Response.ProtoReflect.Descriptor instead.
func (*BlogService_SaveBlogPost_Response) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{2}
}

type BlogService_DeleteBlogPost_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (x *BlogService_DeleteBlogPost_Params) Reset() {
	*x = BlogService_DeleteBlogPost_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_DeleteBlogPost_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_DeleteBlogPost_Params) ProtoMessage() {}

func (x *BlogService_DeleteBlogPost_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_DeleteBlogPost_Params.ProtoReflect.Descriptor instead.
func (*BlogService_DeleteBlogPost_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{3}
}

func (x *BlogService_DeleteBlogPost_Params) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type BlogService_DeleteBlogPost_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_DeleteBlogPost_Response) Reset() {
	*x = BlogService_DeleteBlogPost_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_DeleteBlogPost_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_DeleteBlogPost_Response) ProtoMessage() {}

func (x *BlogService_DeleteBlogPost_Response) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_DeleteBlogPost_Response.ProtoReflect.Descriptor instead.
func (*BlogService_DeleteBlogPost_Response) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{4}
}

type BlogService_NewComment_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_NewComment_Params) Reset() {
	*x = BlogService_NewComment_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_NewComment_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_NewComment_Params) ProtoMessage() {}

func (x *BlogService_NewComment_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_NewComment_Params.ProtoReflect.Descriptor instead.
func (*BlogService_NewComment_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{5}
}

type BlogService_SaveComment_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_SaveComment_Params) Reset() {
	*x = BlogService_SaveComment_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_SaveComment_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_SaveComment_Params) ProtoMessage() {}

func (x *BlogService_SaveComment_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_SaveComment_Params.ProtoReflect.Descriptor instead.
func (*BlogService_SaveComment_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{6}
}

type BlogService_SaveComment_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_SaveComment_Response) Reset() {
	*x = BlogService_SaveComment_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_SaveComment_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_SaveComment_Response) ProtoMessage() {}

func (x *BlogService_SaveComment_Response) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_SaveComment_Response.ProtoReflect.Descriptor instead.
func (*BlogService_SaveComment_Response) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{7}
}

type BlogService_DeleteComment_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_DeleteComment_Params) Reset() {
	*x = BlogService_DeleteComment_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_DeleteComment_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_DeleteComment_Params) ProtoMessage() {}

func (x *BlogService_DeleteComment_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_DeleteComment_Params.ProtoReflect.Descriptor instead.
func (*BlogService_DeleteComment_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{8}
}

type BlogService_DeleteComment_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_DeleteComment_Response) Reset() {
	*x = BlogService_DeleteComment_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_DeleteComment_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_DeleteComment_Response) ProtoMessage() {}

func (x *BlogService_DeleteComment_Response) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_DeleteComment_Response.ProtoReflect.Descriptor instead.
func (*BlogService_DeleteComment_Response) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{9}
}

type BlogService_ReplyToComment_Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_ReplyToComment_Params) Reset() {
	*x = BlogService_ReplyToComment_Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_ReplyToComment_Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_ReplyToComment_Params) ProtoMessage() {}

func (x *BlogService_ReplyToComment_Params) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_ReplyToComment_Params.ProtoReflect.Descriptor instead.
func (*BlogService_ReplyToComment_Params) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{10}
}

type BlogService_ReplyToComment_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlogService_ReplyToComment_Response) Reset() {
	*x = BlogService_ReplyToComment_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogService_ReplyToComment_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogService_ReplyToComment_Response) ProtoMessage() {}

func (x *BlogService_ReplyToComment_Response) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogService_ReplyToComment_Response.ProtoReflect.Descriptor instead.
func (*BlogService_ReplyToComment_Response) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{11}
}

var File_blog_service_proto protoreflect.FileDescriptor

var file_blog_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x1a, 0x0d, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x02, 0x0a, 0x1e, 0x42,
	0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x4e, 0x65, 0x77, 0x42, 0x6c,
	0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23,
	0x0a, 0x0d, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x66, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x42, 0x0a, 0x1f, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x5f, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x21, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x21, 0x42,
	0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x1f, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x22, 0x25, 0x0a, 0x23, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x5f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x42, 0x6c, 0x6f, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x20, 0x0a, 0x1e, 0x42, 0x6c, 0x6f,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x22, 0x0a, 0x20, 0x42,
	0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x22, 0x0a, 0x20, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x24, 0x0a, 0x22, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x21, 0x42, 0x6c, 0x6f,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x25,
	0x0a, 0x23, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x54, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x98, 0x05, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0b, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0c, 0x53, 0x61,
	0x76, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x53,
	0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x28, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68,
	0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x28, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x2a, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42,
	0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x4e, 0x65, 0x77, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0e, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x5f,
	0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x27, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x65, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x27, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x29, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73,
	0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x54, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x2a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x26, 0x48, 0x01, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x6f, 0x6d, 0x76, 0x37, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blog_service_proto_rawDescOnce sync.Once
	file_blog_service_proto_rawDescData = file_blog_service_proto_rawDesc
)

func file_blog_service_proto_rawDescGZIP() []byte {
	file_blog_service_proto_rawDescOnce.Do(func() {
		file_blog_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_service_proto_rawDescData)
	})
	return file_blog_service_proto_rawDescData
}

var file_blog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_blog_service_proto_goTypes = []interface{}{
	(*BlogService_NewBlogPost_Params)(nil),      // 0: blogs.BlogService_NewBlogPost_Params
	(*BlogService_SaveBlogPost_Params)(nil),     // 1: blogs.BlogService_SaveBlogPost_Params
	(*BlogService_SaveBlogPost_Response)(nil),   // 2: blogs.BlogService_SaveBlogPost_Response
	(*BlogService_DeleteBlogPost_Params)(nil),   // 3: blogs.BlogService_DeleteBlogPost_Params
	(*BlogService_DeleteBlogPost_Response)(nil), // 4: blogs.BlogService_DeleteBlogPost_Response
	(*BlogService_NewComment_Params)(nil),       // 5: blogs.BlogService_NewComment_Params
	(*BlogService_SaveComment_Params)(nil),      // 6: blogs.BlogService_SaveComment_Params
	(*BlogService_SaveComment_Response)(nil),    // 7: blogs.BlogService_SaveComment_Response
	(*BlogService_DeleteComment_Params)(nil),    // 8: blogs.BlogService_DeleteComment_Params
	(*BlogService_DeleteComment_Response)(nil),  // 9: blogs.BlogService_DeleteComment_Response
	(*BlogService_ReplyToComment_Params)(nil),   // 10: blogs.BlogService_ReplyToComment_Params
	(*BlogService_ReplyToComment_Response)(nil), // 11: blogs.BlogService_ReplyToComment_Response
	(*User)(nil),    // 12: blogs.User
	(*Post)(nil),    // 13: blogs.Post
	(*Comment)(nil), // 14: blogs.Comment
}
var file_blog_service_proto_depIdxs = []int32{
	12, // 0: blogs.BlogService_NewBlogPost_Params.user:type_name -> blogs.User
	13, // 1: blogs.BlogService_SaveBlogPost_Params.post:type_name -> blogs.Post
	13, // 2: blogs.BlogService_DeleteBlogPost_Params.post:type_name -> blogs.Post
	0,  // 3: blogs.BlogService.NewBlogPost:input_type -> blogs.BlogService_NewBlogPost_Params
	1,  // 4: blogs.BlogService.SaveBlogPost:input_type -> blogs.BlogService_SaveBlogPost_Params
	3,  // 5: blogs.BlogService.DeleteBlogPost:input_type -> blogs.BlogService_DeleteBlogPost_Params
	5,  // 6: blogs.BlogService.NewComment:input_type -> blogs.BlogService_NewComment_Params
	6,  // 7: blogs.BlogService.SaveComment:input_type -> blogs.BlogService_SaveComment_Params
	8,  // 8: blogs.BlogService.DeleteComment:input_type -> blogs.BlogService_DeleteComment_Params
	10, // 9: blogs.BlogService.ReplyToComment:input_type -> blogs.BlogService_ReplyToComment_Params
	13, // 10: blogs.BlogService.NewBlogPost:output_type -> blogs.Post
	2,  // 11: blogs.BlogService.SaveBlogPost:output_type -> blogs.BlogService_SaveBlogPost_Response
	4,  // 12: blogs.BlogService.DeleteBlogPost:output_type -> blogs.BlogService_DeleteBlogPost_Response
	14, // 13: blogs.BlogService.NewComment:output_type -> blogs.Comment
	7,  // 14: blogs.BlogService.SaveComment:output_type -> blogs.BlogService_SaveComment_Response
	9,  // 15: blogs.BlogService.DeleteComment:output_type -> blogs.BlogService_DeleteComment_Response
	11, // 16: blogs.BlogService.ReplyToComment:output_type -> blogs.BlogService_ReplyToComment_Response
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_blog_service_proto_init() }
func file_blog_service_proto_init() {
	if File_blog_service_proto != nil {
		return
	}
	file_schemas_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blog_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_NewBlogPost_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_SaveBlogPost_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_SaveBlogPost_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_DeleteBlogPost_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_DeleteBlogPost_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_NewComment_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_SaveComment_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_SaveComment_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_DeleteComment_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_DeleteComment_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_ReplyToComment_Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogService_ReplyToComment_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_service_proto_goTypes,
		DependencyIndexes: file_blog_service_proto_depIdxs,
		MessageInfos:      file_blog_service_proto_msgTypes,
	}.Build()
	File_blog_service_proto = out.File
	file_blog_service_proto_rawDesc = nil
	file_blog_service_proto_goTypes = nil
	file_blog_service_proto_depIdxs = nil
}
