// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: paging.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasNextPage bool   `protobuf:"varint,1,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPrevPage bool   `protobuf:"varint,2,opt,name=has_prev_page,json=hasPrevPage,proto3" json:"has_prev_page,omitempty"`
	StartCursor string `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	EndCursor   string `protobuf:"bytes,4,opt,name=end_cursor,json=endCursor,proto3" json:"end_cursor,omitempty"`
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{0}
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetHasPrevPage() bool {
	if x != nil {
		return x.HasPrevPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil {
		return x.EndCursor
	}
	return ""
}

type PostConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Edges    []*PostEdge `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo *PageInfo   `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
}

func (x *PostConnection) Reset() {
	*x = PostConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostConnection) ProtoMessage() {}

func (x *PostConnection) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostConnection.ProtoReflect.Descriptor instead.
func (*PostConnection) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{1}
}

func (x *PostConnection) GetEdges() []*PostEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *PostConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type PostEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Post `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *PostEdge) Reset() {
	*x = PostEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEdge) ProtoMessage() {}

func (x *PostEdge) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEdge.ProtoReflect.Descriptor instead.
func (*PostEdge) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{2}
}

func (x *PostEdge) GetNode() *Post {
	if x != nil {
		return x.Node
	}
	return nil
}

type UserConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Edges    []*UserEdge `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo *PageInfo   `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{3}
}

func (x *UserConnection) GetEdges() []*UserEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *UserConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type UserEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *User `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *UserEdge) Reset() {
	*x = UserEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEdge) ProtoMessage() {}

func (x *UserEdge) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEdge.ProtoReflect.Descriptor instead.
func (*UserEdge) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{4}
}

func (x *UserEdge) GetNode() *User {
	if x != nil {
		return x.Node
	}
	return nil
}

type CommentConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Edges    []*CommentEdge `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo *PageInfo      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
}

func (x *CommentConnection) Reset() {
	*x = CommentConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentConnection) ProtoMessage() {}

func (x *CommentConnection) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentConnection.ProtoReflect.Descriptor instead.
func (*CommentConnection) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{5}
}

func (x *CommentConnection) GetEdges() []*CommentEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *CommentConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type CommentEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Comment `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *CommentEdge) Reset() {
	*x = CommentEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentEdge) ProtoMessage() {}

func (x *CommentEdge) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentEdge.ProtoReflect.Descriptor instead.
func (*CommentEdge) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{6}
}

func (x *CommentEdge) GetNode() *Comment {
	if x != nil {
		return x.Node
	}
	return nil
}

type PostForwardCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostForwardCursor) Reset() {
	*x = PostForwardCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostForwardCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostForwardCursor) ProtoMessage() {}

func (x *PostForwardCursor) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostForwardCursor.ProtoReflect.Descriptor instead.
func (*PostForwardCursor) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{7}
}

type PostBackwardCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostBackwardCursor) Reset() {
	*x = PostBackwardCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostBackwardCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBackwardCursor) ProtoMessage() {}

func (x *PostBackwardCursor) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBackwardCursor.ProtoReflect.Descriptor instead.
func (*PostBackwardCursor) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{8}
}

type UserForwardCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserForwardCursor) Reset() {
	*x = UserForwardCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserForwardCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserForwardCursor) ProtoMessage() {}

func (x *UserForwardCursor) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserForwardCursor.ProtoReflect.Descriptor instead.
func (*UserForwardCursor) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{9}
}

type UserBackwardCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserBackwardCursor) Reset() {
	*x = UserBackwardCursor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paging_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBackwardCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBackwardCursor) ProtoMessage() {}

func (x *UserBackwardCursor) ProtoReflect() protoreflect.Message {
	mi := &file_paging_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBackwardCursor.ProtoReflect.Descriptor instead.
func (*UserBackwardCursor) Descriptor() ([]byte, []int) {
	return file_paging_proto_rawDescGZIP(), []int{10}
}

var File_paging_proto protoreflect.FileDescriptor

var file_paging_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x1a, 0x0d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4e, 0x65,
	0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x70, 0x72,
	0x65, 0x76, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68,
	0x61, 0x73, 0x50, 0x72, 0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x67, 0x0a, 0x0e,
	0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26,
	0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x64, 0x67, 0x65, 0x52,
	0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2b, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x64, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x22, 0x67, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2b, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x45, 0x64, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x6d, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a,
	0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x64, 0x67,
	0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x45, 0x64, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x6f,
	0x73, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22,
	0x14, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x77, 0x61, 0x72, 0x64, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x77, 0x61, 0x72, 0x64, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x42, 0x26, 0x48, 0x01, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x6f, 0x6d, 0x76, 0x37, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paging_proto_rawDescOnce sync.Once
	file_paging_proto_rawDescData = file_paging_proto_rawDesc
)

func file_paging_proto_rawDescGZIP() []byte {
	file_paging_proto_rawDescOnce.Do(func() {
		file_paging_proto_rawDescData = protoimpl.X.CompressGZIP(file_paging_proto_rawDescData)
	})
	return file_paging_proto_rawDescData
}

var file_paging_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_paging_proto_goTypes = []interface{}{
	(*PageInfo)(nil),           // 0: paging.PageInfo
	(*PostConnection)(nil),     // 1: paging.PostConnection
	(*PostEdge)(nil),           // 2: paging.PostEdge
	(*UserConnection)(nil),     // 3: paging.UserConnection
	(*UserEdge)(nil),           // 4: paging.UserEdge
	(*CommentConnection)(nil),  // 5: paging.CommentConnection
	(*CommentEdge)(nil),        // 6: paging.CommentEdge
	(*PostForwardCursor)(nil),  // 7: paging.PostForwardCursor
	(*PostBackwardCursor)(nil), // 8: paging.PostBackwardCursor
	(*UserForwardCursor)(nil),  // 9: paging.UserForwardCursor
	(*UserBackwardCursor)(nil), // 10: paging.UserBackwardCursor
	(*Post)(nil),               // 11: blogs.Post
	(*User)(nil),               // 12: blogs.User
	(*Comment)(nil),            // 13: blogs.Comment
}
var file_paging_proto_depIdxs = []int32{
	2,  // 0: paging.PostConnection.edges:type_name -> paging.PostEdge
	0,  // 1: paging.PostConnection.page_info:type_name -> paging.PageInfo
	11, // 2: paging.PostEdge.node:type_name -> blogs.Post
	4,  // 3: paging.UserConnection.edges:type_name -> paging.UserEdge
	0,  // 4: paging.UserConnection.page_info:type_name -> paging.PageInfo
	12, // 5: paging.UserEdge.node:type_name -> blogs.User
	6,  // 6: paging.CommentConnection.edges:type_name -> paging.CommentEdge
	0,  // 7: paging.CommentConnection.page_info:type_name -> paging.PageInfo
	13, // 8: paging.CommentEdge.node:type_name -> blogs.Comment
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_paging_proto_init() }
func file_paging_proto_init() {
	if File_paging_proto != nil {
		return
	}
	file_schemas_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_paging_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostForwardCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostBackwardCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserForwardCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paging_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBackwardCursor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paging_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paging_proto_goTypes,
		DependencyIndexes: file_paging_proto_depIdxs,
		MessageInfos:      file_paging_proto_msgTypes,
	}.Build()
	File_paging_proto = out.File
	file_paging_proto_rawDesc = nil
	file_paging_proto_goTypes = nil
	file_paging_proto_depIdxs = nil
}
