# This is the entrypoint/root for all of our defined schemas on the separate schemas folder.

type Query {
  # Used to search for a specific entity on the entire data source. If no results were found by
  # the query.
  globalSearch(keyword: String, category: [String!]): SearchResults!
  
  # List the most recently published posts by anyone in the blog API.
  globalLatestPosts(
    first: Int
    after: PostForwardCursor
    last: Int
    before: PostBackwardCursor): PostConnection!
  
  author(id: Float, uuid: String): Author!
}

type Mutation {

  # superOps are the group of operations that must be rate limited, these are also
  # the most vulnerable commands exposed in the server, as it can modify restricted resources.
  superOps: SuperMutations!

  # Mutations related to users are defined in this type. We shuold consider adding a rate limiting
  # features to this as it can be abused by anyone.
  userOps: UserMutations!
  
}
