
type SearchResultsStats {
  peopleCount: Float!
  postsCount: Float!
  commentsCount: Float!
}

type SearchResults {
  keyword: String!
  people(input: SearchResultPeopleFilter): UserConnection!
  posts(input: SearchResultPostFilter): PostConnection!
  comments(input: SearchResultCommentFilter): CommentConnection!
  stats: SearchResultsStats!
  startTime: Time!
  endTime: Time!
}

input SearchResultPeopleFilter {

}

input SearchResultPostFilter {

}

input SearchResultCommentFilter {

}